# Generated by Django 5.2.17 on 2026-10-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('flat_no', models.CharField(blank=True, default='', max_length=255)),
                ('street_address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('selected_lat', models.FloatField(blank=True, null=True)),
                ('selected_lng', models.FloatField(blank=True, null=True)),
                ('delivery_distance_km', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'ONLINE')], max_length=20)),
                ('status', models.CharField(choices=[('ORDER_PLACED', 'ORDER_PLACED'), ('PREPARING', 'PREPARING'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURN_REQUESTED', 'RETURN_REQUESTED'), ('RETURN_APPROVED', 'RETURN_APPROVED'), ('RETURN_REJECTED', 'RETURN_REJECTED'), ('RETURNED', 'RETURNED')], default='ORDER_PLACED', max_length=50)),
                ('delivery_type', models.CharField(default='COURIER', max_length=50)),
                ('estimated_delivery', models.CharField(blank=True, default='', max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('return_requested_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('help_requested_at', models.DateTimeField(blank=True, null=True)),
                ('help_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(db_index=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN')], default='USER', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('image_url', models.TextField(blank=True, default='')),
                ('delivery_type', models.CharField(default='FARM_DELIVERY', max_length=50)),
                ('tracking_type', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_radius_km', models.IntegerField(default=10)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('freshness_label', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
